### ISSUE TITLE
Please include the binary

### ISSUE THREAD

**Issue by istepaniuk** [franeklubi/dino#2]
A suggestion: We normally leave binaries out of repos for size and portability. In this case, saving those few bytes prevents less experienced users from giving it a go in a VM.

**Comment by franeklubi** [comment]
Hi! Both the binary and the generated floppy image are included in the [releases](https://github.com/franeklubi/dino/releases) section of the repo.

Do You maybe have any suggestions on how should I make this clearer?

**Comment by istepaniuk** [comment]
OOPS!!!! Sorry, that is perfect. To answer your question, maybe swap "How to play" with "How to compile" so impatient silly people like me don't go the long route. Impressive work btw, thanks for sharing!

**Comment by franeklubi** [comment]
Thanks for the suggestion!

I think that swapping the sections is the sensible thing to do.

Fixed by f7ac8e2.
